# Generated by Django 4.2 on 2023-04-15 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.car'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordercar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.car'),
        ),
        migrations.AddField(
            model_name='ordercar',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='cars',
            field=models.ManyToManyField(through='orders.OrderCar', to='warehouse.car'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
