# Generated by Django 4.2 on 2023-04-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('performance', 'Performance'), ('future', 'Future')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('engine', models.CharField(blank=True, max_length=10, null=True)),
                ('warehouse_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.category')),
            ],
        ),
    ]
