# Generated by Django 4.2 on 2023-04-18 19:09

import DRF_CarDealer.apps.cars.models
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='Lexus', max_length=6)),
                ('model', models.CharField(max_length=7)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('engine', models.CharField(blank=True, max_length=10, null=True)),
                ('engine_displacement', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electricity', 'Electricity')], max_length=15, null=True)),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('torque', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('drive_wheels', models.CharField(blank=True, choices=[('awd', 'AWD'), ('rwd', 'RWD'), ('fwd', 'FWD')], max_length=3, null=True)),
                ('acceleration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('warehouse_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images')),
                ('car', models.ImageField(default='lexus.jpg', upload_to='car_images', verbose_name=DRF_CarDealer.apps.cars.models.Car)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('performance', 'Performance'), ('future', 'Future')], max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='cars.category')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category'),
        ),
    ]
